# Generated by Django 2.1.2 on 2018-11-21 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('username', models.CharField(max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
